version: '3.8'

services:
  app:
    image: ${IMAGE_URI}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    networks:
      - raota-net
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xms3g -Xmx3g
      - OCI_VAULT_ID=${OCI_VAULT_ID}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8080/actuator/health/readiness || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    stop_grace_period: 1m
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 5G
        reservations:
          memory: 3G
      update_config:
        parallelism: 1
        delay: 15s
        monitor: 45s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 15s
        monitor: 45s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1

networks:
  raota-net:
    driver: overlay
    ipam:
      config:
        - subnet: 10.10.1.0/24
