ALTER TABLE tb_member_profile
    ADD COLUMN logs_public BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN visits_public BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN posts_public BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN comments_public BOOLEAN NOT NULL DEFAULT TRUE;
